apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: laiuz90gj-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/laiuz90gj-java-quarkus-gitops